namespace Skinora.Shared.Enums;

public enum NotificationType
{
    TRANSACTION_INVITE,
    BUYER_ACCEPTED,
    ITEM_ESCROWED,
    PAYMENT_RECEIVED,
    TRADE_OFFER_SENT_TO_BUYER,
    TRANSACTION_COMPLETED,
    SELLER_PAYMENT_SENT,
    TIMEOUT_WARNING,
    TRANSACTION_CANCELLED,
    TRANSACTION_FLAGGED,
    PAYMENT_INCORRECT,
    LATE_PAYMENT_REFUNDED,
    ITEM_RETURNED,
    PAYMENT_REFUNDED,
    DISPUTE_RESULT,
    FLAG_RESOLVED,
    ADMIN_FLAG_ALERT,
    ADMIN_ESCALATION,
    ADMIN_PAYMENT_FAILURE,
    ADMIN_STEAM_BOT_ISSUE
}
