/**
 * TypeScript enum definitions matching C# backend (06 §2).
 * Values are string literals to match EF Core string storage (HasConversion).
 */

// §2.1 — 13 values
export enum TransactionStatus {
  CREATED = "CREATED",
  ACCEPTED = "ACCEPTED",
  TRADE_OFFER_SENT_TO_SELLER = "TRADE_OFFER_SENT_TO_SELLER",
  ITEM_ESCROWED = "ITEM_ESCROWED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  TRADE_OFFER_SENT_TO_BUYER = "TRADE_OFFER_SENT_TO_BUYER",
  ITEM_DELIVERED = "ITEM_DELIVERED",
  COMPLETED = "COMPLETED",
  CANCELLED_TIMEOUT = "CANCELLED_TIMEOUT",
  CANCELLED_SELLER = "CANCELLED_SELLER",
  CANCELLED_BUYER = "CANCELLED_BUYER",
  CANCELLED_ADMIN = "CANCELLED_ADMIN",
  FLAGGED = "FLAGGED",
}

// §2.2 — 2 values
export enum StablecoinType {
  USDT = "USDT",
  USDC = "USDC",
}

// §2.3 — 2 values
export enum BuyerIdentificationMethod {
  STEAM_ID = "STEAM_ID",
  OPEN_LINK = "OPEN_LINK",
}

// §2.4 — 4 values
export enum CancelledByType {
  TIMEOUT = "TIMEOUT",
  SELLER = "SELLER",
  BUYER = "BUYER",
  ADMIN = "ADMIN",
}

// §2.5 — 9 values
export enum BlockchainTransactionType {
  BUYER_PAYMENT = "BUYER_PAYMENT",
  SELLER_PAYOUT = "SELLER_PAYOUT",
  BUYER_REFUND = "BUYER_REFUND",
  EXCESS_REFUND = "EXCESS_REFUND",
  WRONG_TOKEN_INCOMING = "WRONG_TOKEN_INCOMING",
  WRONG_TOKEN_REFUND = "WRONG_TOKEN_REFUND",
  SPAM_TOKEN_INCOMING = "SPAM_TOKEN_INCOMING",
  LATE_PAYMENT_REFUND = "LATE_PAYMENT_REFUND",
  INCORRECT_AMOUNT_REFUND = "INCORRECT_AMOUNT_REFUND",
}

// §2.6 — 4 values
export enum BlockchainTransactionStatus {
  DETECTED = "DETECTED",
  PENDING = "PENDING",
  CONFIRMED = "CONFIRMED",
  FAILED = "FAILED",
}

// §2.7 — 3 values
export enum TradeOfferDirection {
  TO_SELLER = "TO_SELLER",
  TO_BUYER = "TO_BUYER",
  RETURN_TO_SELLER = "RETURN_TO_SELLER",
}

// §2.8 — 6 values
export enum TradeOfferStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
}

// §2.9 — 3 values
export enum DisputeType {
  PAYMENT = "PAYMENT",
  DELIVERY = "DELIVERY",
  WRONG_ITEM = "WRONG_ITEM",
}

// §2.10 — 3 values
export enum DisputeStatus {
  OPEN = "OPEN",
  ESCALATED = "ESCALATED",
  CLOSED = "CLOSED",
}

// §2.11 — 4 values
export enum FraudFlagType {
  PRICE_DEVIATION = "PRICE_DEVIATION",
  HIGH_VOLUME = "HIGH_VOLUME",
  ABNORMAL_BEHAVIOR = "ABNORMAL_BEHAVIOR",
  MULTI_ACCOUNT = "MULTI_ACCOUNT",
}

// §2.12 — 3 values
export enum ReviewStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

// §2.13 — 20 values
export enum NotificationType {
  TRANSACTION_INVITE = "TRANSACTION_INVITE",
  BUYER_ACCEPTED = "BUYER_ACCEPTED",
  ITEM_ESCROWED = "ITEM_ESCROWED",
  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",
  TRADE_OFFER_SENT_TO_BUYER = "TRADE_OFFER_SENT_TO_BUYER",
  TRANSACTION_COMPLETED = "TRANSACTION_COMPLETED",
  SELLER_PAYMENT_SENT = "SELLER_PAYMENT_SENT",
  TIMEOUT_WARNING = "TIMEOUT_WARNING",
  TRANSACTION_CANCELLED = "TRANSACTION_CANCELLED",
  TRANSACTION_FLAGGED = "TRANSACTION_FLAGGED",
  PAYMENT_INCORRECT = "PAYMENT_INCORRECT",
  LATE_PAYMENT_REFUNDED = "LATE_PAYMENT_REFUNDED",
  ITEM_RETURNED = "ITEM_RETURNED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",
  DISPUTE_RESULT = "DISPUTE_RESULT",
  FLAG_RESOLVED = "FLAG_RESOLVED",
  ADMIN_FLAG_ALERT = "ADMIN_FLAG_ALERT",
  ADMIN_ESCALATION = "ADMIN_ESCALATION",
  ADMIN_PAYMENT_FAILURE = "ADMIN_PAYMENT_FAILURE",
  ADMIN_STEAM_BOT_ISSUE = "ADMIN_STEAM_BOT_ISSUE",
}

// §2.14 — 3 values
export enum NotificationChannel {
  EMAIL = "EMAIL",
  TELEGRAM = "TELEGRAM",
  DISCORD = "DISCORD",
}

// §2.15 — 4 values
export enum PlatformSteamBotStatus {
  ACTIVE = "ACTIVE",
  RESTRICTED = "RESTRICTED",
  BANNED = "BANNED",
  OFFLINE = "OFFLINE",
}

// §2.16 — 5 values
export enum MonitoringStatus {
  ACTIVE = "ACTIVE",
  POST_CANCEL_24H = "POST_CANCEL_24H",
  POST_CANCEL_7D = "POST_CANCEL_7D",
  POST_CANCEL_30D = "POST_CANCEL_30D",
  STOPPED = "STOPPED",
}

// §2.17 — 4 values
export enum OutboxMessageStatus {
  PENDING = "PENDING",
  PROCESSED = "PROCESSED",
  DEFERRED = "DEFERRED",
  FAILED = "FAILED",
}

// §2.18 — 3 values
export enum ActorType {
  USER = "USER",
  SYSTEM = "SYSTEM",
  ADMIN = "ADMIN",
}

// §2.19 — 12 values
export enum AuditAction {
  WALLET_DEPOSIT = "WALLET_DEPOSIT",
  WALLET_WITHDRAW = "WALLET_WITHDRAW",
  WALLET_ESCROW_LOCK = "WALLET_ESCROW_LOCK",
  WALLET_ESCROW_RELEASE = "WALLET_ESCROW_RELEASE",
  WALLET_REFUND = "WALLET_REFUND",
  DISPUTE_RESOLVED = "DISPUTE_RESOLVED",
  MANUAL_REFUND = "MANUAL_REFUND",
  USER_BANNED = "USER_BANNED",
  USER_UNBANNED = "USER_UNBANNED",
  ROLE_CHANGED = "ROLE_CHANGED",
  SYSTEM_SETTING_CHANGED = "SYSTEM_SETTING_CHANGED",
  WALLET_ADDRESS_CHANGED = "WALLET_ADDRESS_CHANGED",
}

// §2.20 — 4 values
export enum TimeoutFreezeReason {
  MAINTENANCE = "MAINTENANCE",
  STEAM_OUTAGE = "STEAM_OUTAGE",
  BLOCKCHAIN_DEGRADATION = "BLOCKCHAIN_DEGRADATION",
  EMERGENCY_HOLD = "EMERGENCY_HOLD",
}

// §2.21 — 2 values
export enum FraudFlagScope {
  ACCOUNT_LEVEL = "ACCOUNT_LEVEL",
  TRANSACTION_PRE_CREATE = "TRANSACTION_PRE_CREATE",
}

// §2.22 — 5 values
export enum PayoutIssueStatus {
  REPORTED = "REPORTED",
  VERIFYING = "VERIFYING",
  RETRY_SCHEDULED = "RETRY_SCHEDULED",
  ESCALATED = "ESCALATED",
  RESOLVED = "RESOLVED",
}

// §2.23 — 3 values
export enum DeliveryStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
}
