# T16 — Auto-provision Prometheus as datasource for Grafana.
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://skinora-prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: '15s'
      httpMethod: POST
